"""empty message

Revision ID: 477e13d5d70f
Revises: 
Create Date: 2022-03-27 06:28:41.741694

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '477e13d5d70f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('creditRating',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('CompanyName', sa.Float(), nullable=True),
    sa.Column('RequestData', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('ZScoreData', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('ZScoreOutput', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('time_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('time_updated', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('creditRating')
    # ### end Alembic commands ###
